apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksk8sdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      containers:
        - name: wa4c-demo
          image: acrTest1024.azurecr.io/azure-vote-front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: azure-vote-front
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 80
  selector:
    app: azure-vote-front
  type: LoadBalancer
